### ISSUE TITLE
Clarification on encode - encodeContainer vs decode - decodeContainer

### ISSUE THREAD

**Issue by dmateusp** [haskell-works/avro#106]
Hi there!

I'm trying to get familiar with the library, and as an example I tried to expand on the README example and take a Haskell Data structure, encode it to Avro, write it to file and decode it from the file into the original Data structure again.

My first try was using the `encode` and `decode` functions and writing/reading to a file, but it produced invalid Avro (tested with avro-tools.jar)

So I decided to try the encodeContainer / decodeContainer functions instead and that worked, then I started to look into "why" that worked and found the following:

> Avro includes a simple object container file format. A file has a schema, and all objects stored in the file must be written according to that schema, using binary encoding. Objects are stored in blocks that may be compressed. Syncronization markers are used between blocks to permit efficient splitting of files for MapReduce processing.

As I've been using Avro only through high level interfaces such as Spark/Hive before I was unaware of the "Object Container Files" specificity, and that records were organized in "blocks".

Does that mean encodeContainer and decodeContainer are the only suitable functions for dealing with files ? (because they deal with blocks), and encode / decode are only suitable for exchange of Avro messages through HTTP requests ?

**Comment by AlexeyRaga** [comment]
> Does that mean encodeContainer and decodeContainer are the only suitable functions for dealing with files?
Sort of. As you have found, Avro specification talks about [Object Container Files](https://avro.apache.org/docs/1.8.2/spec.html#Object+Container+Files) and this is what you usually use when writing many avro-encoded values into a file.
Strictly speaking, it is not "because they deal with blocks" but because of Spark/Hive/etc. support Avro by following the specification. The reason for storing values in blocks allow streaming'ish behaviour, especially when containers are big.
Avro containers also contain schema, which is useful because it makes the file self-contained: we always know what is inside and how to read it.

> encode / decode are only suitable for exchange of Avro messages through HTTP requests?
Not specifically HTTP, but yes, useful for for messaging. Also, each value inside a container is serialised this way.

**Comment by dmateusp** [comment]
hey @AlexeyRaga thanks for the clarification!

**Comment by dmateusp** [comment]
I've added the code I was talking about in a Gist in case new-comers find this Issue: https://gist.github.com/dmateusp/aa2ebcbb973e307f77d665739e589809
