### ISSUE TITLE
I can encode Avro inconsistent with my schema

### ISSUE THREAD

**Issue by jessekempf** [haskell-works/avro#58]
I just ran into a (more complex) bug which mostly reduces to the fact that if I have:

```
import qualified Data.Avro.Types as T
import qualified Data.Avro.Schema as S

newtype Foo = Foo Double

instance HasAvroSchema Foo where
  schema = pure S.Long

instance ToAvro Foo where
  toAvro (Foo val) = T.Double val

instance FromAvro Foo where
  ...
```

The problem is caught at decode time, and in a non-obvious way, not encode time and in an obvious way.

Is this intended, or is it an oversight?

**Comment by AlexeyRaga** [comment]
Is it problematic because  you specify `S.Long` in `HasAvroSchema` but give it  `T.Double` in an instance?
Are you saying that we should be enforcing at the type level (or at least validating at the encoding time) that these types match?
I don't think that we intentionally not enforcing it, just that it has never been implemented or thought of...

**Comment by jessekempf** [comment]
Yes.

In a perfect world the answer is "This is Haskell", so this should be caught at compile time using the type system. That would require a fundamental change to the way the library works and I'm not entirely sure how one would do it.

Given the world we live in, we already have the schema at encoding-time, so we could detect the problem at encoding-time. It then becomes a matter of whether to make `toAvro` produce a monadic value, or instead crash if there's a mismatch between schema and output.

**Comment by AlexeyRaga** [comment]
Since we don't have a clear plan about fixing this issue (and whether it is indeed an issue)  I'll close it for now
