### ISSUE TITLE
Enable CCI to use orbs

### ISSUE THREAD

**Issue by AlexeyRaga** [haskell-works/avro#75]
@TomMD Hi Tom,
I'd like to use CircleCI Orb (https://circleci.com/orbs/registry/orb/haskell-works/haskell-build) for building this project.
You can read more about orbs here: https://circleci.com/docs/2.0/using-orbs/

Would it be possible to enable this settings for the Galois organisation in CircleCI?

![image](https://user-images.githubusercontent.com/1394391/50476098-f6598480-0a1a-11e9-90ca-e9de552629fa.png)

**Comment by TomMD** [comment]
Hurm, that is a good question @AlexeyRaga .  I'll need to ask the admin, which I can do on Tuesday.

Is this urgent? If this is presently a significant issue then it might be the straw that moves the project over to your namespace after all.

**Comment by TomMD** [comment]
Thinking for more than a second on it - we should probably transfer to your namespace.  Care to click the button? I don't think I can since I can't create repos in your org.  That said, I'm also happy to talk to the admin on Tuesday if you'd rather leave it here.

Why?  Well obviously I haven't had work projects pull me back to this code like I had expected.  Certainly you are using it heavily and should be able to take necessary actions without an intermediary.  If anyone objects then I'm all ears, I just don't see any strong reason to keep it under the GaloisInc organization.

**Comment by AlexeyRaga** [comment]
Fair enough! I am OK with transferring it under `haskell-works`.
Unless there are no major objections (@TikhonJelvis?) I will make a transfer in a couple of days.

**Comment by TikhonJelvis** [comment]
Transferring sounds perfectly reasonable to me. 

We should update the links on the Hackage page when we do.

**Comment by AlexeyRaga** [comment]
Thanks everyone, the transfer has happened, a new release with the updated links has been published to Hackage.
