### ISSUE TITLE
Don't reexport the orphan Show (a -> b) instance

### ISSUE THREAD

**Issue by neongreen** [haskell-works/avro#81]
Is there a good reason why it's exported?

https://github.com/haskell-works/avro/blob/2a370134befaa8dd2627e9efa6463ed1a9acadd5/src/Data/Avro/Schema.hs#L79

**Comment by AlexeyRaga** [comment]
We don't re-export `Text.Show.Function, do we?
We import `Text.Show.Function ()` instances to be able to derive `Show` for `Schema`. It is impossible otherwise because `Schema` has function members.

I think we could give `Schema` a manual instance of `Show`, or think of removing the ability to `Show` schema (which has been quite useful for debugging but may not be used for any "real" code).

Frankly, `Schema` is one of these "evel" types that declares partial functions, etc. Can be refactored, but I worry a bit about compatibility. Also, it'd be great to think about how to remove these "lookup" functions from the schema data type, which may simplify a lot of things, such as lifting it to TH, etc...

**Comment by neongreen** [comment]
All instances that you import or otherwise make available in a module are always exported from that module. Just doing `import Text.Show.Function ()` is enough for this instance to propagate to `Data.Avro` and then all modules elsewhere that import _anything_ from `Data.Avro`.

**Comment by AlexeyRaga** [comment]
I see that, I am just pointing to the fact that we don't re-export it explicitly. The reason it bubbles up is that `deriving Show` on `Schema`.
I see how it is not ideal though.

**Comment by neongreen** [comment]
> The reason it bubbles up is that `deriving Show` on `Schema`.

No, it would bubble up even if you didn't do `deriving Show` on `Schema`.

> I think we could give `Schema` a manual instance of `Show`, or think of removing the ability to `Show` schema (which has been quite useful for debugging but may not be used for any "real" code).

You could ask GHC to dump the derived instance and then paste it into the code. It does look like the resulting instance would be annoying to have in code, though. I don't know what is the best solution here.

**Comment by AlexeyRaga** [comment]
> No, it would bubble up even if you didn't do `deriving Show` on `Schema`.
If we didn't do that we wouldn't need to import that orphan instance :)

One way of solving it would be not to provide `Show` instance for `Schema`. 
There is a way to dump it as json, and it is probably even more convenient for debugging...
I don't know if we really need `Show` for `Schema`, but it might be convenient for someone here...

How big is the issue?

**Comment by TikhonJelvis** [comment]
Having a `Show` instance is really handy for debugging and using GHCi.

Personally, I would prefer to wrap the lookup function in `Schema` in a `newtype`. This would break backwards compatibility but it would be an easy fix, and I doubt there is any code outside encoding/decoding that uses that part of `Schema`.

**Comment by TikhonJelvis** [comment]
The reexported `Show` instance is already confusing people who depend on `avro` in our internal codebase, and there's no way to suppress it without forking the whole package.

I think it's worth breaking backwards compatibility to fix this problem. I'm happy to submit a PR wrapping the function in a newtype if we're willing to do this.

**Comment by AlexeyRaga** [comment]
I am good with that. Don't think it'd be noticed anyway because I doubt that anyone would use these functions directly.

I am curious if there is a way to remove these functions completely. It looks like they are there for optimisation, an alternative would require doing a lookup of some sort.
But how costly would it be to do such a lookup? Or how costly would it be to build such functions on the fly?..

**Comment by AlexeyRaga** [comment]
Fixing `deconflict` I am looking at `Union`s now. 
It looks like `unionLookup` function is only used in one place: in `getAvroOf` function to get the value type by its index. 

From the spec:

> A union is encoded by first writing a long value indicating the zero-based position within the union of the schema of its value. 

So it must _always_ be a 0-based index.

What I think is that we can update union definition from:
```
      | Union { options     :: NonEmpty Type
              , unionLookup :: Int64 -> Maybe Type
              }
```
to
```
      | Union { options     :: Vector Type }
```

and since `Vector` provides a constant-time indexed lookup we can get rid of `unionLookup` function.

This should also allow us to simplify `deriving` because after removing a function it should be possible to use the very same type in TH (a function prevented it from being lifted to TH as fas as I remember).

@TikhonJelvis what do you think? Am I missing anything here?
