### ISSUE TITLE
Decoding of Avros with `codec = deflate` doesn't obey spec

### ISSUE THREAD

**Issue by alexbiehl** [haskell-works/avro#83]
The spec states

> The "deflate" codec writes the data block using the deflate algorithm as specified in RFC 1951, and > typically implemented using the zlib library. Note that this format (unlike the "zlib format" in RFC 1950) does not have a checksum.

Now, when I try to decode a container with `codec = deflate` I get 

```
Header error: Header checksum failed
```

Which is an error message from pure-zlib. But according to spec neither header nor checksums should be serialized and instead the raw format defined by RFC 1951 should be used.

**Comment by alexbiehl** [comment]
It seems that `pure-zlib` is not offering a "raw deflate". `zlib` does, would you accept a PR switching from `pure-zlib` to `zlib`? 

This would answer my question from https://github.com/haskell-works/avro/issues/53#issuecomment-467915451.

**Comment by AlexeyRaga** [comment]
Since the Avro spec says that

> Implementations are required to support the following codecs: "null" and "deflate"

I think that we should support it and I personally would be very grateful for such a PR. There is already an issue to support compression at the "writing" side, which can be targeted easier after we support decompression.

From my POV the only "disadvantage" of using `zlib` over `pure-zlib` is that `zlib` uses C. 

I think I am OK with that, are there any other downsides?
